kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: quay.io/jonnrb/three_oh_two
    username:
      from_secret: quay_username
    password:
      from_secret: quay_password
