---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: docker
  image: plugins/docker
  settings:
    password:
      from_secret: quay_password
    repo: quay.io/jonnrb/three_oh_two
    username:
      from_secret: quay_username

...
